<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9683kpt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9683kpt/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9683kpt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9683kpt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9683kpt\appProdProjectContainer([
    'container.build_hash' => '9683kpt',
    'container.build_id' => '70b41f30',
    'container.build_time' => 1635555839,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9683kpt');
