<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0ft7rl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0ft7rl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV0ft7rl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV0ft7rl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV0ft7rl\appDevDebugProjectContainer([
    'container.build_hash' => 'V0ft7rl',
    'container.build_id' => '461c01e7',
    'container.build_time' => 1635555899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0ft7rl');
