<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPckjeqn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPckjeqn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPckjeqn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPckjeqn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPckjeqn\appProdProjectContainer([
    'container.build_hash' => 'Pckjeqn',
    'container.build_id' => 'c5ce8ab5',
    'container.build_time' => 1635498561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPckjeqn');
