<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4s4kqe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4s4kqe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC4s4kqe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC4s4kqe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC4s4kqe\appProdProjectContainer([
    'container.build_hash' => 'C4s4kqe',
    'container.build_id' => '87cd2e00',
    'container.build_time' => 1635555839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4s4kqe');
